services:
  - type: web
    name: iicpc-platform
    runtime: node
    region: oregon
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: ""
      - key: NEXT_PUBLIC_WS_URL
        value: ""
